### ISSUE TITLE
DIsabled emmet

### ISSUE THREAD

**Issue by Hmyanya97** [zignd/HTML-CSS-Class-Completion#351]
Issue Type: <b>Bug</b>

This cause problems

Extension version: 1.20.0
VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.18362
Restricted Mode: No

**Comment by zignd** [comment]
Please provide more information.

**Comment by Oziboi** [comment]
HI

I've been learning of vs code, html and css only at this stage.  For some reason, I no longer have emmet.  I'm not an IT person.  I rang Microsoft who refused to help because, well, vs code is free and i guess they couldn't care less otherwise.  Anyone out there with a simple solution?  thanks, Mark
