### ISSUE TITLE
Not working on Code - Insiders 1.11.0

### ISSUE THREAD

**Issue by vikrantnegi** [Zignd/HTML-CSS-Class-Completion#43]
I'm not able to use the plugin in Code - Insiders 1.11.0

**Comment by darpots** [comment]
Same issue, same insiders version. 

Simply no auto complete pop up.

**Comment by salacis** [comment]
Great plugin, needs a fix soon! :)

**Comment by Uranbold** [comment]
Yeah it's not working......

**Comment by narospol** [comment]
version 1.11.1 not working

**Comment by andersea** [comment]
Hi! I am the author of [HTML Class Suggestions](https://marketplace.visualstudio.com/items?itemName=AndersEAndersen.html-class-suggestions).

I got hit by this as well.

The breakage is due to the following new 'feature': https://code.visualstudio.com/updates/v1_11#_intellisense-in-comments. You can reenable the old behaviour by setting the 'strings' option to true.

By default, the suggestions are still available, but are not triggered automatically. You have to trigger them manually with ctrl+space.

I am currently looking for a way to force the setting in my extension, which isn't working at the moment, I don't know why yet.

References:
Microsoft/vscode#24464
andersea/HTMLClassSuggestionsVSCode#9

**Comment by MainaWycliffe** [comment]
@andersea i can confirm, your solution worked form. Thanks. One more question do i have to change the settings each time i install VSCode?

**Comment by andersea** [comment]
The settings are stored in your home directory and persists between updates.

https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations
