### ISSUE TITLE
Make Visual Studio Code crash in Ubuntu 16.04

### ISSUE THREAD

**Issue by dangviettuan** [zignd/HTML-CSS-Class-Completion#57]
Visual Studio Code stop working after update version 1.6.0

**Comment by utklasad** [comment]
Same problem here. I have to disable the extension in order to make Visual Studio Code work on Ubuntu 17.04. With the extension enabled everything freezes and all windows, explorer etc. stop working.

Seems to work for smaller projects - but not with bigger ones. Worked with earlier versions of this extension.

**Comment by DuncanFaulkner** [comment]
I have had the same issue, though I only noticed the issue when I upgraded to 1.13.1 of vs code, once I had disabled this extension as per @otijhuis comments on https://github.com/Microsoft/vscode/issues/28867 vs code stopped crashing and started working again.


ubuntu 16.04

**Comment by idomusha** [comment]
I think it's the same problem than #52

**Comment by zignd** [comment]
I guess this issue has been fixed in the latest update. Thanks to Erich Gamma for this great pull request #90.
