### ISSUE TITLE
Add support for Emmet Snippets

### ISSUE THREAD

**Issue by VSDekar** [zignd/HTML-CSS-Class-Completion#59]
Awesome extension!

I don't know if that is even possible. But i write most of my HTML code with Emmet Snippet. It would be nice if we get there the same IntelliSense experience.

**Comment by zignd** [comment]
Glad you like it :)

I'll look into that as soon as I manage to fix one issue that is causing the Visual Studio Code to freeze for some workspaces (#58).

**Comment by ZionInc** [comment]
@VSDekar . A quick and dirty way in the meanwhile.

Change in [extension.ts](https://github.com/zignd/HTML-CSS-Class-Completion/blob/master/src/extension.ts)

```
const htmlRegex = /class=["|']([\w- ]*$)/; 
to 
const htmlRegex = /\.([\w- ]*$)/;    
```

**Comment by WaqasIbrahim** [comment]
@ZionInc This wouldn't work because there are other operations on classes found after matching the regex.

@zignd I opened a duplicate issue #79 because I did not find this one when I searched. I was working on this feature when my HDD failed and I lost it but I have got a fair idea on how to implement this. I will work on this feature and then you can review. Is that fine? Thanks

**Comment by zignd** [comment]
@WaqasIbrahim It's totally fine, I'll gladly review it once you finish it. :)

**Comment by WaqasIbrahim** [comment]
@zignd I have submitted a pull request #86.
